/********************************************************************
* dict_AliSkimmedDataAnalysisMaker.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict_AliSkimmedDataAnalysisMaker.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledict_AliSkimmedDataAnalysisMaker();
extern void G__cpp_setup_inheritancedict_AliSkimmedDataAnalysisMaker();
extern void G__cpp_setup_typetabledict_AliSkimmedDataAnalysisMaker();
extern void G__cpp_setup_memvardict_AliSkimmedDataAnalysisMaker();
extern void G__cpp_setup_globaldict_AliSkimmedDataAnalysisMaker();
extern void G__cpp_setup_memfuncdict_AliSkimmedDataAnalysisMaker();
extern void G__cpp_setup_funcdict_AliSkimmedDataAnalysisMaker();
extern void G__set_cpp_environmentdict_AliSkimmedDataAnalysisMaker();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "V0FlatAna.h"
#include "TrackFlatAna.h"
#include "AliSkimmedDataAnalysisMaker.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TClass;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TBuffer;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMemberInspector;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TObject;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TString;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TFile;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TTree;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TBranch;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_V0FlatAna;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TrackFlatAna;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TH1F;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_TH2F;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_THnSparseTlETArrayFgR;
extern G__linked_taginfo G__dict_AliSkimmedDataAnalysisMakerLN_AliSkimmedDataAnalysisMaker;

/* STUB derived class for protected member access */
